# Generated by Django 6.0.6 on 2026-06-28 10:19

import django.db.models.deletion
import projects.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=projects.models.logo_upload_path, verbose_name='Logo')),
                ('color', models.CharField(default='#2563eb', max_length=20, verbose_name='Farbe')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon')),
                ('active', models.BooleanField(default=True, verbose_name='Status')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=25, max_digits=10, verbose_name='Stundenlohn')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='invoices.customer', verbose_name='Kunde')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='invoices.customercontact', verbose_name='Ansprechpartner')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contacts', to='projects.project', verbose_name='Projekt')),
            ],
            options={
                'unique_together': {('project', 'contact')},
            },
        ),
        migrations.CreateModel(
            name='ProjectLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_links', to='invoices.customerlocation', verbose_name='Standort')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_locations', to='projects.project', verbose_name='Projekt')),
            ],
            options={
                'unique_together': {('project', 'location')},
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Eigentümer'), ('manager', 'Manager'), ('employee', 'Mitarbeiter')], default='employee', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
    ]
