# Generated by Django 6.0.6 on 2026-06-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=255, verbose_name='Firmenname')),
                ('name', models.CharField(max_length=255, verbose_name='Geschäftsführer')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo')),
                ('slogan', models.CharField(blank=True, max_length=255, verbose_name='Slogan')),
                ('color', models.CharField(default='#0f172a', max_length=20, verbose_name='Farbe')),
                ('street', models.CharField(max_length=255, verbose_name='Straße')),
                ('zip', models.CharField(max_length=20, verbose_name='PLZ')),
                ('city', models.CharField(max_length=255, verbose_name='Ort')),
                ('country', models.CharField(default='Deutschland', max_length=100, verbose_name='Land')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='E-Mail')),
                ('website', models.URLField(blank=True, max_length=100, verbose_name='Webseite')),
                ('tax_number', models.CharField(blank=True, max_length=100, verbose_name='Steuernummer')),
                ('vat_number', models.CharField(blank=True, max_length=100, verbose_name='USt-IdNr.')),
                ('is_small_business', models.BooleanField(default=False, verbose_name='Kleinunternehmer (§19 UStG)')),
                ('small_business_text', models.TextField(blank=True, verbose_name='Kleinunternehmer Hinweis')),
                ('invoice_header_text', models.TextField(blank=True, verbose_name='Rechnungszusatztext')),
                ('offer_header_text', models.TextField(blank=True, verbose_name='Angebotszusatztext')),
                ('reminder_header_text', models.TextField(blank=True, verbose_name='Mahnungszusatztext')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Bank')),
                ('iban', models.CharField(blank=True, max_length=50, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=50, verbose_name='BIC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Firmeneinstellung',
                'verbose_name_plural': 'Firmeneinstellungen',
            },
        ),
    ]
