# Generated by Django 6.0.6 on 2026-06-24 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='BIC'),
        ),
        migrations.CreateModel(
            name='DocumentNumberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_prefix', models.CharField(default='RE', max_length=20)),
                ('invoice_next_number', models.PositiveIntegerField(default=1)),
                ('cancel_prefix', models.CharField(default='ST', max_length=20)),
                ('cancel_next_number', models.PositiveIntegerField(default=1)),
                ('offer_prefix', models.CharField(default='ANG', max_length=20)),
                ('offer_next_number', models.PositiveIntegerField(default=1)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='number_settings', to='core.companysetting')),
            ],
        ),
    ]
