# Generated by Django 6.0.6 on 2026-06-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_companysetting_invoice_number_documentnumbersettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentNumberSettings',
        ),
    ]
