# Generated by Django 6.0.6 on 2026-06-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_documentnumbersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='offer_header_text',
            field=models.TextField(blank=True, verbose_name='Angebotszusatztext'),
        ),
    ]
