# Generated by Django 6.0.6 on 2026-06-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_companysetting_offer_header_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysetting',
            name='invoice_number',
        ),
    ]
