# Generated by Django 6.0.6 on 2026-06-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_companysetting_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysetting',
            name='reminder_header_text',
            field=models.TextField(blank=True, verbose_name='Mahnungszusatztext'),
        ),
    ]
