# Generated by Django 6.0.6 on 2026-06-27 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_number', models.CharField(max_length=50, unique=True, verbose_name='Kunden-ID')),
                ('customer_type', models.CharField(choices=[('private', 'Privat'), ('company', 'Unternehmen')], default='company', max_length=20, verbose_name='Kundentyp')),
                ('company_name', models.CharField(max_length=255, verbose_name='Firmenname / Kundenname')),
                ('tax_number', models.CharField(blank=True, max_length=100, verbose_name='Steuernummer')),
                ('vat_number', models.CharField(blank=True, max_length=100, verbose_name='UST-IdNr')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('active', models.BooleanField(default=True, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kunde',
                'verbose_name_plural': 'Kunden',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('item', 'Artikel'), ('time', 'Zeiterfassung'), ('expense', 'Ausgabe')], default='item', max_length=20, verbose_name='Quelle')),
                ('description', models.CharField(max_length=255, verbose_name='Beschreibung')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Menge')),
                ('unit', models.CharField(max_length=50, verbose_name='Einheit')),
                ('unit_price_net', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einzelpreis Netto')),
                ('unit_tax_rate', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='MwSt. Satz (%)')),
                ('service_period_from', models.DateField(blank=True, null=True, verbose_name='Leistungszeitraum von')),
                ('service_period_to', models.DateField(blank=True, null=True, verbose_name='Leistungszeitraum bis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rechnungsposition',
                'verbose_name_plural': 'Rechnungspositionen',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('service', 'Dienstleistung'), ('product', 'Ware')], default='product', max_length=20, verbose_name='Art')),
                ('description', models.CharField(max_length=255, verbose_name='Beschreibung')),
                ('price_net', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preis Netto')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='MwSt. Satz (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Posten',
                'verbose_name_plural': 'Posten',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_number', models.CharField(blank=True, max_length=50, verbose_name='Angebotsnummer')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('sent', 'Versendet'), ('accepted', 'Akzeptiert'), ('rejected', 'Abgelehnt'), ('expired', 'Ausgelaufen')], default='draft', max_length=20, verbose_name='Status')),
                ('issue_date', models.DateField(verbose_name='Angebotsdatum')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Gültig bis')),
                ('note', models.TextField(blank=True, verbose_name='Notiz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='offer_pdfs/', verbose_name='PDF')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='PDF erstellt am')),
                ('tax_number', models.CharField(blank=True, max_length=100, verbose_name='Steuernummer Kunde')),
                ('vat_number', models.CharField(blank=True, max_length=100, verbose_name='USt-IdNr Kunde')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Ansprechpartner')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail Ansprechpartner')),
                ('contact_phone', models.CharField(blank=True, max_length=100, verbose_name='Telefon Ansprechpartner')),
                ('location_name', models.CharField(max_length=255, verbose_name='Standort')),
                ('location_street', models.CharField(blank=True, max_length=255, verbose_name='Straße')),
                ('location_city', models.CharField(blank=True, max_length=255, verbose_name='Ort')),
                ('location_zip', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('location_country', models.CharField(blank=True, max_length=100, verbose_name='Land')),
            ],
            options={
                'verbose_name': 'Angebot',
                'verbose_name_plural': 'Angebote',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Beschreibung')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Menge')),
                ('unit', models.CharField(max_length=50, verbose_name='Einheit')),
                ('unit_price_net', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einzelpreis Netto')),
                ('unit_tax_rate', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='MwSt. Satz (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Angebotsposition',
                'verbose_name_plural': 'Angebotspositionen',
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_number', models.CharField(blank=True, max_length=50, verbose_name='Mahnungsnummer')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('sent', 'Versendet'), ('paid', 'Bezahlt'), ('canceled', 'Storniert'), ('expired', 'Frist abgelaufen')], default='draft', max_length=20, verbose_name='Status')),
                ('level', models.PositiveSmallIntegerField(default=1, help_text='1 = Erste Mahnung, 2 = Zweite Mahnung, 3 = Letzte Mahnung', verbose_name='Mahnstufe')),
                ('issue_date', models.DateField(verbose_name='Mahndatum')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Neue Zahlungsfrist')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mahngebühr')),
                ('note', models.TextField(blank=True, verbose_name='Hinweis')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reminder_pdfs/', verbose_name='PDF')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='PDF erstellt am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mahnung',
                'verbose_name_plural': 'Mahnungen',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Bezeichnung')),
                ('short_name', models.CharField(max_length=20, verbose_name='Kürzel')),
            ],
            options={
                'verbose_name': 'Einheit',
                'verbose_name_plural': 'Einheiten',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nachname')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=100, verbose_name='Telefon')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='invoices.customer', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'Ansprechpartner',
                'verbose_name_plural': 'Ansprechpartner',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='CustomerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Bezeichnung')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='Ort')),
                ('street', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Land')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='invoices.customer', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'Standort',
                'verbose_name_plural': 'Standorte',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DocumentNumberSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_format', models.CharField(default='RE-{year}-{number}', max_length=100, verbose_name='Rechnungsformat')),
                ('invoice_next_number', models.PositiveIntegerField(default=1, verbose_name='Rechnungs ID (nächste)')),
                ('cancel_format', models.CharField(default='ST-{year}-{number}', max_length=100, verbose_name='Stornoformat')),
                ('cancel_next_number', models.PositiveIntegerField(default=1, verbose_name='Storno ID (nächste)')),
                ('offer_format', models.CharField(default='ANG-{year}-{number}', max_length=100, verbose_name='Angebotsformat')),
                ('offer_next_number', models.PositiveIntegerField(default=1, verbose_name='Angebots ID (nächste)')),
                ('reminder_format', models.CharField(default='M-{year}-{number}', max_length=100, verbose_name='Mahnungsformat')),
                ('reminder_next_number', models.PositiveIntegerField(default=1, verbose_name='Mahnungs ID (nächste)')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='number_settings', to='core.companysetting', verbose_name='Unternehmen')),
            ],
            options={
                'verbose_name': 'Dokumentnummer',
                'verbose_name_plural': 'Dokumentnummern',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Rechnungsnummer')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('sent', 'Versendet'), ('paid', 'Bezahlt'), ('overdue', 'Überfällig'), ('canceled', 'Storniert')], default='draft', max_length=20, verbose_name='Status')),
                ('issue_date', models.DateField(verbose_name='Rechnungsdatum')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Fälligkeitsdatum')),
                ('note', models.TextField(blank=True, verbose_name='Notiz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='invoice_pdfs/', verbose_name='PDF')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='PDF erstellt am')),
                ('cancel_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Stornorechnungsnummer')),
                ('pdf_canceled_file', models.FileField(blank=True, null=True, upload_to='invoice_pdfs/', verbose_name='Stornorechnung')),
                ('pdf_canceled_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='Stornorechnung erstellt am')),
                ('tax_number', models.CharField(blank=True, max_length=100, verbose_name='Steuernummer Kunde')),
                ('vat_number', models.CharField(blank=True, max_length=100, verbose_name='USt-IdNr Kunde')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Ansprechpartner')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail Ansprechpartner')),
                ('contact_phone', models.CharField(blank=True, max_length=100, verbose_name='Telefon Ansprechpartner')),
                ('location_name', models.CharField(max_length=255, verbose_name='Standort')),
                ('location_street', models.CharField(blank=True, max_length=255, verbose_name='Straße')),
                ('location_city', models.CharField(blank=True, max_length=255, verbose_name='Ort')),
                ('location_zip', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('location_country', models.CharField(blank=True, max_length=100, verbose_name='Land')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='invoices.customer', verbose_name='Kunde')),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
                'ordering': ['-issue_date'],
            },
        ),
    ]
