# Generated by Django 6.0.6 on 2026-06-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='pdf_canceled_file',
            field=models.FileField(blank=True, null=True, upload_to='invoice_pdfs/', verbose_name='Stornorechnung'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_canceled_generated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Stornorechnung erstellt am'),
        ),
    ]
