# Generated by Django 6.0.6 on 2026-06-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_documentnumbersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentnumbersettings',
            name='cancel_prefix',
        ),
        migrations.RemoveField(
            model_name='documentnumbersettings',
            name='invoice_prefix',
        ),
        migrations.RemoveField(
            model_name='documentnumbersettings',
            name='offer_prefix',
        ),
        migrations.AddField(
            model_name='documentnumbersettings',
            name='cancel_format',
            field=models.CharField(default='ST-{year}-{number}', max_length=100),
        ),
        migrations.AddField(
            model_name='documentnumbersettings',
            name='invoice_format',
            field=models.CharField(default='RE-{year}-{number}', max_length=100),
        ),
        migrations.AddField(
            model_name='documentnumbersettings',
            name='offer_format',
            field=models.CharField(default='ANG-{year}-{number}', max_length=100),
        ),
    ]
