# Generated by Django 6.0.6 on 2026-06-24 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_documentnumbersettings'),
        ('invoices', '0005_remove_documentnumbersettings_cancel_prefix_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentnumbersettings',
            options={'verbose_name': 'Dokumentnummer', 'verbose_name_plural': 'Dokumentnummern'},
        ),
        migrations.AlterField(
            model_name='documentnumbersettings',
            name='cancel_format',
            field=models.CharField(default='ST-{year}-{number}', max_length=100, verbose_name='Stornoformat'),
        ),
        migrations.AlterField(
            model_name='documentnumbersettings',
            name='cancel_next_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Storno ID (nächste)'),
        ),
        migrations.AlterField(
            model_name='documentnumbersettings',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='number_settings', to='core.companysetting', verbose_name='Unternehmen'),
        ),
        migrations.AlterField(
            model_name='documentnumbersettings',
            name='invoice_format',
            field=models.CharField(default='RE-{year}-{number}', max_length=100, verbose_name='Rechnungsformat'),
        ),
        migrations.AlterField(
            model_name='documentnumbersettings',
            name='invoice_next_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Rechnungs ID (nächste)'),
        ),
        migrations.AlterField(
            model_name='documentnumbersettings',
            name='offer_format',
            field=models.CharField(default='ANG-{year}-{number}', max_length=100, verbose_name='Angebotsformat'),
        ),
        migrations.AlterField(
            model_name='documentnumbersettings',
            name='offer_next_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Angebots ID (nächste)'),
        ),
    ]
