# Generated by Django 6.0.6 on 2026-06-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_alter_documentnumbersettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cancel_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Stornorechnungsnummer'),
        ),
    ]
