# Generated by Django 6.0.6 on 2026-06-24 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_invoice_cancel_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_number', models.CharField(max_length=50, unique=True, verbose_name='Mahnungsnummer')),
                ('level', models.PositiveSmallIntegerField(default=1, help_text='1 = Erste Mahnung, 2 = Zweite Mahnung, 3 = Letzte Mahnung', verbose_name='Mahnstufe')),
                ('issue_date', models.DateField(verbose_name='Mahndatum')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Neue Zahlungsfrist')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Mahngebühr')),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Verzugszinsen')),
                ('note', models.TextField(blank=True, verbose_name='Hinweis')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reminder_pdfs/', verbose_name='PDF')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='PDF erstellt am')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminders', to='invoices.invoice', verbose_name='Rechnung')),
            ],
            options={
                'verbose_name': 'Mahnung',
                'verbose_name_plural': 'Mahnungen',
                'ordering': ['-created_at'],
            },
        ),
    ]
