# Generated by Django 6.0.6 on 2026-06-24 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_reminder'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_number', models.CharField(max_length=50, unique=True, verbose_name='Angebotsnummer')),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('sent', 'Versendet'), ('accepted', 'Akzeptiert'), ('rejected', 'Abgelehnt'), ('expired', 'Ausgelaufen')], default='draft', max_length=20, verbose_name='Status')),
                ('issue_date', models.DateField(verbose_name='Angebotsdatum')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Gültig bis')),
                ('note', models.TextField(blank=True, verbose_name='Notiz')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='offer_pdfs/', verbose_name='PDF')),
                ('pdf_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='PDF erstellt am')),
                ('tax_number', models.CharField(blank=True, max_length=100, verbose_name='Steuernummer Kunde')),
                ('vat_number', models.CharField(blank=True, max_length=100, verbose_name='USt-IdNr Kunde')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Ansprechpartner')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail Ansprechpartner')),
                ('contact_phone', models.CharField(blank=True, max_length=100, verbose_name='Telefon Ansprechpartner')),
                ('location_name', models.CharField(max_length=255, verbose_name='Standort')),
                ('location_street', models.CharField(blank=True, max_length=255, verbose_name='Straße')),
                ('location_city', models.CharField(blank=True, max_length=255, verbose_name='Ort')),
                ('location_zip', models.CharField(blank=True, max_length=20, verbose_name='PLZ')),
                ('location_country', models.CharField(blank=True, max_length=100, verbose_name='Land')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='invoices.customer', verbose_name='Kunde')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='projects.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Angebot',
                'verbose_name_plural': 'Angebote',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Beschreibung')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Menge')),
                ('unit', models.CharField(max_length=50, verbose_name='Einheit')),
                ('unit_price_net', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einzelpreis Netto')),
                ('unit_tax_rate', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='MwSt. Satz (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.item', verbose_name='Artikel')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.offer', verbose_name='Angebot')),
            ],
            options={
                'verbose_name': 'Angebotsposition',
                'verbose_name_plural': 'Angebotspositionen',
            },
        ),
    ]
