# Generated by Django 6.0.6 on 2026-06-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_offer_offeritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='service_period_from',
            field=models.DateField(blank=True, null=True, verbose_name='Leistungszeitraum von'),
        ),
        migrations.AddField(
            model_name='item',
            name='service_period_to',
            field=models.DateField(blank=True, null=True, verbose_name='Leistungszeitraum bis'),
        ),
    ]
