# Generated by Django 6.0.6 on 2026-06-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_item_service_period_from_item_service_period_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='service_period_from',
        ),
        migrations.RemoveField(
            model_name='item',
            name='service_period_to',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='service_period_from',
            field=models.DateField(blank=True, null=True, verbose_name='Leistungszeitraum von'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='service_period_to',
            field=models.DateField(blank=True, null=True, verbose_name='Leistungszeitraum bis'),
        ),
    ]
