# Generated by Django 6.0.6 on 2026-06-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_remove_item_service_period_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='project',
        ),
    ]
