# Generated by Django 6.0.6 on 2026-06-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_remove_offer_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('draft', 'Entwurf'), ('sent', 'Versendet'), ('paid', 'Bezahlt'), ('partial', 'Teilweise bezahlt'), ('cancelled', 'Storniert'), ('expired', 'Frist abgelaufen')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
