# Generated by Django 6.0.6 on 2026-06-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentnumbersettings',
            name='offer_format',
            field=models.CharField(default='M-{year}-{number}', max_length=100, verbose_name='Mahnungsformat'),
        ),
        migrations.AlterField(
            model_name='documentnumbersettings',
            name='offer_next_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Mahnungs ID (nächste)'),
        ),
    ]
