# Generated by Django 6.0.6 on 2026-06-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_alter_documentnumbersettings_offer_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentnumbersettings',
            name='reminder_format',
            field=models.CharField(default='M-{year}-{number}', max_length=100, verbose_name='Mahnungsformat'),
        ),
        migrations.AddField(
            model_name='documentnumbersettings',
            name='reminder_next_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Mahnungs ID (nächste)'),
        ),
        migrations.AlterField(
            model_name='documentnumbersettings',
            name='offer_format',
            field=models.CharField(default='ANG-{year}-{number}', max_length=100, verbose_name='Angebotsformat'),
        ),
        migrations.AlterField(
            model_name='documentnumbersettings',
            name='offer_next_number',
            field=models.PositiveIntegerField(default=1, verbose_name='Angebots ID (nächste)'),
        ),
    ]
