# Generated by Django 6.0.6 on 2026-06-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0018_alter_reminder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Rechnungsnummer'),
        ),
    ]
