# Generated by Django 6.0.6 on 2026-06-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0019_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Angebotsnummer'),
        ),
    ]
