# Generated by Django 6.0.6 on 2026-06-27 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0020_alter_offer_offer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Mahnungsnummer'),
        ),
    ]
