# Generated by Django 6.0.6 on 2026-06-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0021_alter_reminder_reminder_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Verzugszinssatz (%)'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Verzugszinsen Betrag'),
        ),
    ]
