# Generated by Django 6.0.6 on 2026-06-27 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0022_reminder_interest_rate_alter_reminder_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='interest_days',
            field=models.PositiveIntegerField(default=0, verbose_name='Verzugstage'),
        ),
    ]
