# Generated by Django 6.0.6 on 2026-06-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0023_reminder_interest_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='interest',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Verzugszinsen Betrag'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='interest_days',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Verzugstage'),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, verbose_name='Verzugszinssatz (%)'),
        ),
    ]
