# Generated by Django 6.0.6 on 2026-06-27 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0024_alter_reminder_interest_alter_reminder_interest_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='interest',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='interest_days',
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='interest_rate',
        ),
    ]
