# Generated by Django 6.0.6 on 2026-06-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_invoices_invoices_invoices_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='invoices_invoices_invoices_cancel',
            field=models.BooleanField(default=False, help_text='Benutzer darf Rechnungen stornieren.', verbose_name='Rechnung stornieren'),
        ),
    ]
