# Generated by Django 6.0.6 on 2026-06-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_role_invoices_invoices_invoices_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='invoices_invoices_invoices_cancel_download',
            field=models.BooleanField(default=False, help_text='Benutzer darf Stornorechnungen herunterladen.', verbose_name='Stornorechnung Download'),
        ),
    ]
