# Generated by Django 6.0.6 on 2026-06-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_role_invoices_invoices_invoices_cancel_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='invoices_invoices_invoices_cancel_download',
        ),
        migrations.AddField(
            model_name='role',
            name='invoices_invoices_invoices_paid',
            field=models.BooleanField(default=False, help_text='Benutzer darf Rechnungsstatus ändern.', verbose_name='Rechnung auf bezahlt setzen'),
        ),
    ]
