# Generated by Django 6.0.6 on 2026-06-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_role_invoices_invoices_invoices_cancel_download_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='invoices_offers_add',
            field=models.BooleanField(default=False, help_text='Benutzer darf Angebote für Kunden erstellen.', verbose_name='Angebot erstellen'),
        ),
        migrations.AddField(
            model_name='role',
            name='invoices_offers_offers_download',
            field=models.BooleanField(default=False, help_text='Benutzer darf Angebote herunterladen.', verbose_name='Angebot herunterladen'),
        ),
        migrations.AddField(
            model_name='role',
            name='invoices_offers_offers_item_add',
            field=models.BooleanField(default=False, help_text='Benutzer darf Positionen hinzufügen.', verbose_name='Angebotsposition hinzufügen'),
        ),
        migrations.AddField(
            model_name='role',
            name='invoices_offers_offers_item_delete',
            field=models.BooleanField(default=False, help_text='Benutzer darf Positionen löschen.', verbose_name='Angebotsposition löschen'),
        ),
        migrations.AddField(
            model_name='role',
            name='invoices_offers_offers_preview',
            field=models.BooleanField(default=False, help_text='Benutzer darf Vorschauen öffnen.', verbose_name='Angebotsvorschau anzeigen'),
        ),
        migrations.AddField(
            model_name='role',
            name='invoices_offers_offers_status',
            field=models.BooleanField(default=False, help_text='Benutzer darf Angebotsstatus ändern.', verbose_name='Angebotsstatus bearbeiten'),
        ),
        migrations.AddField(
            model_name='role',
            name='invoices_offers_offers_view',
            field=models.BooleanField(default=False, help_text='Benutzer darf Angebotsdetails sehen.', verbose_name='Angebotsdetails anzeigen'),
        ),
        migrations.AddField(
            model_name='role',
            name='invoices_offers_view',
            field=models.BooleanField(default=False, help_text='Benutzer darf Angebote sehen.', verbose_name='Angebote anzeigen'),
        ),
    ]
