# Generated by Django 6.0.6 on 2026-06-28 10:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('travel', 'Anfahrt'), ('work', 'Arbeitszeit')], default='work', max_length=20, verbose_name='Typ')),
                ('activity', models.CharField(blank=True, max_length=255, verbose_name='Tätigkeit')),
                ('start', models.DateTimeField(verbose_name='Beginn')),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('break_minutes', models.PositiveIntegerField(default=0, verbose_name='Pause (Minuten)')),
                ('note', models.TextField(blank=True, verbose_name='Notiz')),
                ('invoiced', models.BooleanField(default=False, verbose_name='Abgerechnet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='projects.project', verbose_name='Projekt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL, verbose_name='Mitarbeiter')),
            ],
            options={
                'verbose_name': 'Zeiterfassung',
                'verbose_name_plural': 'Zeiterfassungen',
                'ordering': ['-start'],
            },
        ),
    ]
